### ISSUE TITLE
Pry error after update pry-inline to support pry 0.13 

### ISSUE THREAD

**Issue by hstastna** [seikichi/pry-inline#9]
Error is thrown after it hits `binding.pry` in the ruby code, for _pry-inline_ 1.0.6 and _pry_ 0.13.0:
```
...
before_session hook failed: NoMethodError: undefined method `inline' for #<Pry::Config:0x0000000004cf3380>
/home/hstastna/.rbenv/versions/2.5.4/lib/ruby/gems/2.5.0/gems/pry-0.13.0/lib/pry/config.rb:250:in `method_missing'
(see pry_instance.hooks.errors to debug)
...
```

Backtrace:
```
[4] pry(#<DashboardController>)> pry_instance.hooks.errors.first.backtrace
=> [
 "gems/pry-0.13.0/lib/pry/config.rb:250:in `method_missing'",
 "gems/pry-inline-1.0.6/lib/pry-inline/code_extension.rb:103:in `min_debug_info_width'",
 "gems/pry-inline-1.0.6/lib/pry-inline/code_extension.rb:39:in `block in print_to_output'",
 "gems/pry-inline-1.0.6/lib/pry-inline/code_extension.rb:34:in `each'",
 "gems/pry-inline-1.0.6/lib/pry-inline/code_extension.rb:34:in `print_to_output'",
 "gems/pry-0.13.0/lib/pry/code.rb:264:in `highlighted'",
 "gems/pry-0.13.0/lib/pry/commands/whereami.rb:108:in `process'",
 "gems/pry-0.13.0/lib/pry/class_command.rb:82:in `call'",
 "gems/pry-0.13.0/lib/pry/command.rb:495:in `call_with_hooks'",
 "gems/pry-0.13.0/lib/pry/command.rb:431:in `block in call_safely'",
 "gems/pry-0.13.0/lib/pry/command.rb:439:in `use_unpatched_symbol'",
 "gems/pry-0.13.0/lib/pry/command.rb:430:in `call_safely'",
 "gems/pry-0.13.0/lib/pry/command.rb:404:in `process_line'",
 "gems/pry-0.13.0/lib/pry/command_set.rb:354:in `process_line'",
 "gems/pry-0.13.0/lib/pry/pry_instance.rb:376:in `run_command'",
 "gems/pry-0.13.0/lib/pry/hooks.rb:20:in `block in default'",
 "gems/pry-0.13.0/lib/pry/hooks.rb:111:in `block in exec_hook'",
 "gems/pry-0.13.0/lib/pry/hooks.rb:109:in `map'",
 "gems/pry-0.13.0/lib/pry/hooks.rb:109:in `exec_hook'",
 "gems/pry-0.13.0/lib/pry/pry_instance.rb:396:in `exec_hook'",
 "gems/pry-0.13.0/lib/pry/repl.rb:48:in `prologue'",
 "gems/pry-0.13.0/lib/pry/repl.rb:37:in `start'",
 "gems/pry-0.13.0/lib/pry/repl.rb:15:in `start'",
 "gems/pry-0.13.0/lib/pry/pry_class.rb:191:in `start'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:117:in `block in resume_pry'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block (2 levels) in run'",
 "gems/byebug-11.1.1/lib/byebug/helpers/eval.rb:94:in `allowing_other_threads'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:30:in `block in run'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `catch'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:29:in `run'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:113:in `resume_pry'",
 "gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:65:in `at_line'",
 "gems/byebug-11.1.1/lib/byebug/context.rb:98:in `at_line'",
 ...
]
```

When using lower version for _pry-inline_, error did not occur and everything worked as expected:
`gem "pry-inline", "<1.0.6"`

**Comment by eliotsykes** [comment]
I can confirm seeing this issue with pry 0.13.0 and pry-inline 1.0.6.

To workaround, use pry 0.12.2 and pry-inline 1.0.5.

**Comment by d4rky-pl** [comment]
Using pry 0.13 with pry-inline 1.0.0 also works without issues

**Comment by seikichi** [comment]
Hi @hstastna , @eliotsykes 

Sorry, I noticed this issue now. Thank you for reporting the issue. I'll check it.

**Comment by seikichi** [comment]
Hi @hstastna, @eliotsykes 

I fixed the problem and released the new version (1.0.7).

Please use pry-inline 1.0.7 and pry 0.13.1 )!= 0.13.0). It seems that there is a bug in 0.13.0 (https://github.com/pry/pry/pull/2126 ).

**Comment by hstastna** [comment]
@eliotsykes Does the fix work for you? Can I close the issue?

**Comment by eliotsykes** [comment]
Thanks for this @seikichi.

@hstastna Yes, I believe you can close this. These versions are working:

✅  pry-inline 1.0.7 with pry 0.12.2
✅  pry-inline 1.0.7 with pry 0.13.1
